# Generated by Django 5.0.3 on 2024-05-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('table_number', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('transfer', 'Transfer'), ('cash', 'Cash')], max_length=10)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('menu_items', models.ManyToManyField(to='menu_app.menu')),
            ],
        ),
    ]
